#!/usr/bin/env python3
"""Clinical chart recipes for cancer-buddy (stdlib only, ZERO medical logic).

Layer 2 of the two-layer design — see chart_core.py for layer 1 (primitives).
Each recipe below composes primitives; it does not own an engine. A chart type
nobody anticipated is a NEW RECIPE built from the same primitives, which is what
lets this skill answer a request outside the catalogue instead of failing over
to "not supported" (references/chart-catalog.md §3, SKILL.md §generalisation).

CHANNEL A — 段D case-summary embed (backwards compatible)
    Drop-in replacement for compute_sparklines.py. Same CLI, same emitted
    fields, same exit codes, byte-identical geometry for trend_charts[] and
    lab_trends[]. New capability is additive (reference_band, reading_note),
    never a change to an existing field.

        python3 render_chart.py --data case_summary_data.json \
            [--out enriched.json] [--longitudinal L.json] [--labs labs.json]

CHANNEL B — standalone chart file (paths B and C)
    Assembles a complete self-contained HTML file. No template renderer, no JS,
    no external font, no CDN.

        python3 render_chart.py --chart trend --from-longitudinal L.json \
            --metric CEA --out-html cea.html
        python3 render_chart.py --chart <recipe> --spec spec.json --out-html f.html

Exit codes:
    0  — ok
    2  — bad invocation / unreadable / malformed input
    3  — anti-fabrication gate failed (a plotted value is absent from the source)
    4  — caption/title gate failed (a verdict-bearing phrase reached the output)
    5  — eligibility gate failed (series not eligible to be graphed)
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from chart_core import (  # noqa: E402
    AMBER, BAND, CARD, CRIT, INK, LADDER, MUTED, MUTED_DEEP, PRIMARY,
    PRIMARY_HI, RULE, FS_AXIS, FS_BODY, FS_TITLE, FS_VALUE,
    Svg, TimeAxis, ValueAxis, esc, fmt, page, parse_reference_range,
    LabelPlacer, censoring, point_colour, range_status, row_y, stack_rows,
    text_width, to_float, to_ordinal, truncate,
)

# Fixed viewBoxes for channel A — the template's <svg viewBox> MUST match.
HERO_W, HERO_H, HERO_PAD = 360.0, 120.0, 12.0
SPARK_W, SPARK_H, SPARK_PAD = 120.0, 32.0, 5.0
_EPS = 1e-9

# Channel B canvas (viewBox unit == 1pt).
FIG_W, FIG_PAD = 460.0, 30.0

BADGE_GAP = 26.0
BADGE_CY0 = 10.0
BADGE_DY = 15.0


# ═════════════════════════════════════════════════════════════════════════════
# G-CHART-1 — the verdict gate (floor only)
# ═════════════════════════════════════════════════════════════════════════════
# A regex list is a FLOOR, not the whole gate. It guarantees the blatant cases
# are caught; judging whether a phrasing amounts to a verdict is a semantic call
# and belongs to the skill's sub-prompt (SKILL.md §title). Never treat a pass
# here as "this caption is fine".
#
# SCOPE — this gate runs on AUTHORED text only: --title, spec-supplied captions,
# and the LLM-filled caption fields in case_summary_data.json. It deliberately
# does NOT run on:
#
#   (a) disclaimers and reading notes generated by the deterministic code below.
#       Two failures forced this. A blanket regex flags the very disclaimer
#       G-CHART-5 REQUIRES ("时间对齐不表示疗效或因果") because it cannot read
#       negation — the sentence denies the verdict it is matched on.
#   (b) clinical strings transcribed from the record. "缓解" inside 诱导缓解方案
#       is a standard regimen name, not a verdict; flagging it would reject a
#       faithfully transcribed chart label and push the pipeline toward quietly
#       renaming what the record says, which is worse than the risk it prevents.
#
# The threat model is "a model wrote a verdict into a caption", not "a fixed
# sentence we already reviewed contains a word". Deterministic output is
# governed by code review; only authored text needs a runtime gate.
VERDICT_PATTERNS = [
    r"有效", r"无效", r"起效", r"见效", r"疗效", r"响应", r"反应良好", r"应答",
    r"进展", r"缓解", r"恶化", r"好转", r"改善", r"变差", r"加重", r"减轻",
    r"复发", r"转移风险", r"控制良好", r"控制不佳", r"稳定期", r"敏感", r"耐药",
    r"预后", r"生存(?:期|率)", r"危险", r"乐观", r"不容乐观", r"严重",
    r"\b(?:CR|PR|SD|PD)\b", r"complete response", r"partial response",
    r"stable disease", r"progressive disease", r"responding", r"remission",
    r"improv(?:ing|ed|ement)", r"worsen(?:ing|ed)", r"deteriorat",
    r"效果(?:好|不好|明显|显著)", r"说明", r"提示", r"意味着", r"表明",
]
_VERDICT_RE = re.compile("|".join(VERDICT_PATTERNS), re.I)


def verdict_violations(*texts):
    """Return [(text, matched_phrase)] for any string carrying a verdict."""
    bad = []
    for t in texts:
        if not t:
            continue
        for m in _VERDICT_RE.finditer(str(t)):
            bad.append((str(t), m.group(0)))
    return bad


# ═════════════════════════════════════════════════════════════════════════════
# Reading notes — the third way between "verdict" and "number readback"
# ═════════════════════════════════════════════════════════════════════════════
# A compliant caption is not automatically a useful one. "CEA: 12.4 → 8.1" just
# reprints what the chart already shows, in the most expensive line on the card.
# A reading note instead answers "how should I read this chart, and can I trust
# it?" — comparability breaks, gaps, what the band is. That is information the
# patient cannot see for themselves but which decides whether the chart means
# anything, and it is what turns the chart into something worth handing to a
# clinician. Every sentence below is a statement about the DATA, never about the
# disease.
def reading_note(points, unit=None, ref=None, ref_source=None):
    """Compose a reading note from data facts only. Returns (note, caveats)."""
    bits, caveats = [], []
    n = len(points)
    if n == 0:
        return "没有可绘制的数据点。", []
    span_txt = ""
    ords_ = [p["o"] for p in points if p.get("o") is not None]
    if len(ords_) >= 2:
        days = max(ords_) - min(ords_)
        span_txt = f"，跨度约 {_humanise_days(days)}"
    bits.append(f"{n} 次记录{span_txt}")

    # comparability: method changes split the series' meaning
    methods = [p.get("method") for p in points if p.get("method")]
    distinct = []
    for m in methods:
        if m not in distinct:
            distinct.append(m)
    if len(distinct) > 1:
        idx = next((i + 1 for i, p in enumerate(points)
                    if p.get("method") and p.get("method") != points[0].get("method")), None)
        where = f"第 {idx} 次起" if idx else "其中"
        caveats.append(f"{where}检测方法或设备变更（{ '、'.join(str(d) for d in distinct) }），"
                       f"不同方法的绝对值不能直接比较，已分段显示。")

    # comparability: unit changes make the series meaningless if merged
    units = [p.get("unit") for p in points if p.get("unit")]
    du = []
    for u in units:
        if u not in du:
            du.append(u)
    if len(du) > 1:
        caveats.append(f"记录中出现不同单位（{'、'.join(str(u) for u in du)}），"
                       f"未做换算，请与主诊团队核对后再比较。")

    # gaps: a long silence changes how the shape should be read
    if len(ords_) >= 3:
        srt = sorted(ords_)
        gaps = [(srt[i + 1] - srt[i], i) for i in range(len(srt) - 1)]
        gmax, gi = max(gaps)
        median = sorted(g for g, _ in gaps)[len(gaps) // 2]
        if median > 0 and gmax >= max(90, median * 3):
            bits.append(f"其中有一段约 {_humanise_days(gmax)} 的空档")

    n_cens = sum(1 for p in points if p.get("censor"))
    if n_cens:
        caveats.append(f"其中 {n_cens} 个结果报告为检测限（如 <5.0），真实数值在该限值之外，"
                       f"图中按限值位置绘制并用方块标记，不代表实测值。")

    # the band, and where it came from
    if ref:
        lo, hi = ref
        if lo is not None and hi is not None:
            bits.append(f"与参考区间 {_num(lo)}–{_num(hi)}{_u(unit)} 对照")
        elif hi is not None:
            bits.append(f"与参考区间上限 {_num(hi)}{_u(unit)} 对照")
        elif lo is not None:
            bits.append(f"与参考区间下限 {_num(lo)}{_u(unit)} 对照")
        if ref_source:
            bits[-1] += f"（区间取自{ref_source}）"
    else:
        caveats.append("本次报告未提供可解析的参考区间，图中不显示区间带。"
                       "不同实验室与方法的参考区间不同，不能套用通用值。")
    return "，".join(bits) + "。", caveats


def _humanise_days(d: int) -> str:
    if d < 45:
        return f"{d} 天"
    if d < 365:
        return f"{round(d / 30.4)} 个月"
    y = d / 365.25
    return f"{y:.1f} 年".replace(".0 ", " ")


def _num(v) -> str:
    f = to_float(v)
    if f is None:
        return str(v)
    return str(int(f)) if abs(f - int(f)) < _EPS else f"{f:g}"


def _u(unit) -> str:
    return f" {unit}" if unit else ""


# ═════════════════════════════════════════════════════════════════════════════
# CHANNEL A — byte-compatible enrichment of case_summary_data.json
# ═════════════════════════════════════════════════════════════════════════════
def _numeric_series(series):
    """Filter to plottable points [(ordinal, value, raw_value)], sorted by day."""
    pts = []
    if not isinstance(series, list):
        return pts
    for p in series:
        if not isinstance(p, dict):
            continue
        v = to_float(p.get("v"))
        o = to_ordinal(p.get("t"))
        if v is None or o is None:
            continue
        pts.append((o, v, p.get("v")))
    pts.sort(key=lambda x: x[0])
    return pts


def _x_axis(ordinals, w: float, pad: float):
    lo, hi = min(ordinals), max(ordinals)
    span = hi - lo
    inner = w - 2 * pad
    if span <= 0:
        cx = pad + inner / 2
        return lambda o: cx, lo, hi
    return lambda o: pad + (o - lo) / span * inner, lo, hi


def _y_of(v: float, vmin: float, vmax: float, h: float, pad: float) -> float:
    inner = h - 2 * pad
    if vmax - vmin < _EPS:
        return h / 2
    return h - pad - (v - vmin) / (vmax - vmin) * inner


def _direction(pts):
    """Direction of the MOST RECENT segment. Retained for backwards
    compatibility of the emitted field; the template no longer renders an arrow
    glyph from it (chart-style.md §red-restraint: a downward arrow is read as
    'improving', which is a verdict we may not give)."""
    if len(pts) < 2:
        return "single" if pts else "flat"
    prev, last = pts[-2][1], pts[-1][1]
    if abs(last - prev) < _EPS:
        return "flat"
    return "down" if last < prev else "up"


def _enrich_series(obj, w, h, pad, with_area: bool, with_dots: bool = False):
    """Inject svg_points / svg_area_d / dots / direction / point_count.

    Byte-identical to compute_sparklines._enrich_series. Do not 'improve' the
    geometry here: the 段D template is a 1:1 golden artefact and its rendered
    output is diffed in CI.
    """
    pts = _numeric_series(obj.get("series"))
    obj["point_count"] = len(pts)
    obj["direction"] = _direction(pts)
    if pts:
        obj["last_value"] = str(pts[-1][2])
        obj["first_value"] = str(pts[0][2])
    else:
        obj["last_value"] = ""
        obj["first_value"] = ""
    if not pts:
        obj["svg_points"] = ""
        if with_area:
            obj["svg_area_d"] = ""
        if with_dots:
            obj["dots"] = []
        return []
    xf, _, _ = _x_axis([o for o, _, _ in pts], w, pad)
    vmin = min(v for _, v, _ in pts)
    vmax = max(v for _, v, _ in pts)
    coords = [(xf(o), _y_of(v, vmin, vmax, h, pad)) for o, v, _ in pts]
    obj["svg_points"] = " ".join(f"{fmt(x)},{fmt(y)}" for x, y in coords) if len(coords) >= 2 else ""
    if with_area:
        if len(coords) >= 2:
            base = h - pad
            d = ["M", f"{fmt(coords[0][0])},{fmt(coords[0][1])}"]
            for x, y in coords[1:]:
                d += ["L", f"{fmt(x)},{fmt(y)}"]
            d += ["L", f"{fmt(coords[-1][0])},{fmt(base)}",
                  "L", f"{fmt(coords[0][0])},{fmt(base)}", "Z"]
            obj["svg_area_d"] = " ".join(d)
        else:
            obj["svg_area_d"] = ""
    if with_dots:
        obj["dots"] = [{"cx": fmt(x), "cy": fmt(y)} for x, y in coords]
    return [raw for _, _, raw in pts]


def _enrich_markers(hero, w, pad):
    """Place treatment-line markers on the hero series' time axis."""
    markers = hero.get("treatment_markers")
    if not isinstance(markers, list) or not markers:
        return
    dict_markers = [m for m in markers if isinstance(m, dict)]
    pts = _numeric_series(hero.get("series"))
    if not pts:
        for i, m in enumerate(dict_markers):
            m["idx"] = i + 1
            t = m.get("t")
            m["marker_date"] = t[:7] if isinstance(t, str) and len(t) >= 7 else (t or "")
            m["marker_x"] = fmt(pad)
            m["marker_x_left"] = fmt(pad - 6)
            m["badge_pct"] = fmt(pad / w * 100)
            m["badge_cy"] = fmt(BADGE_CY0)
            m["badge_ty"] = fmt(BADGE_CY0 + 3.3)
        return
    ordinals = [o for o, _, _ in pts]
    xf, lo, hi = _x_axis(ordinals, w, pad)
    for i, m in enumerate(dict_markers):
        m["idx"] = i + 1
        t = m.get("t")
        m["marker_date"] = t[:7] if isinstance(t, str) and len(t) >= 7 else (t or "")
        o = to_ordinal(t)
        x = pad if o is None else xf(max(lo, min(hi, o)))
        m["_x"] = x
        m["marker_x"] = fmt(x)
        m["marker_x_left"] = fmt(x - 6)
        m["badge_pct"] = fmt(x / w * 100)
    row_last_x = []
    for m in sorted(dict_markers, key=lambda mm: mm["_x"]):
        x = m["_x"]
        row = next((r for r, lx in enumerate(row_last_x) if x - lx >= BADGE_GAP), None)
        if row is None:
            row = len(row_last_x)
            row_last_x.append(x)
        else:
            row_last_x[row] = x
        cy = BADGE_CY0 + row * BADGE_DY
        m["badge_cy"] = fmt(cy)
        m["badge_ty"] = fmt(cy + 3.3)
        del m["_x"]


def _enrich_reference_band(chart):
    """ADDITIVE: reference-range band geometry for the hero chart (C1).

    Emitted as band_y / band_h in the SAME viewBox as svg_points, so the
    template can draw <rect> under the curve. Absent (empty string) when the
    range is missing or unparseable — the template then shows the explicit
    'no parseable reference range' note rather than silently omitting the band,
    because a missing band and a band you happen to sit inside look identical
    otherwise.
    """
    pts = _numeric_series(chart.get("series"))
    raw_ref = chart.get("reference_range")
    ref = parse_reference_range(raw_ref)
    chart["reference_range_text"] = str(raw_ref) if raw_ref else ""
    if not pts or not ref:
        chart["band_y"] = ""
        chart["band_h"] = ""
        chart["has_band"] = ""
        return
    vmin = min(v for _, v, _ in pts)
    vmax = max(v for _, v, _ in pts)
    lo, hi = ref
    # expand the domain so the band is visible even when every point sits inside
    if lo is not None:
        vmin, vmax = min(vmin, lo), max(vmax, lo)
    if hi is not None:
        vmin, vmax = min(vmin, hi), max(vmax, hi)
    y_lo = _y_of(lo, vmin, vmax, HERO_H, HERO_PAD) if lo is not None else HERO_H - HERO_PAD
    y_hi = _y_of(hi, vmin, vmax, HERO_H, HERO_PAD) if hi is not None else HERO_PAD
    top, bottom = min(y_lo, y_hi), max(y_lo, y_hi)
    chart["band_y"] = fmt(top)
    chart["band_h"] = fmt(max(0.0, bottom - top))
    chart["has_band"] = "1"
    # geometry moved: re-derive the curve against the EXPANDED domain so points
    # and band share one scale (otherwise a point could sit visually inside a
    # band it is numerically outside — the most dangerous possible artefact).
    xf, _, _ = _x_axis([o for o, _, _ in pts], HERO_W, HERO_PAD)
    coords = [(xf(o), _y_of(v, vmin, vmax, HERO_H, HERO_PAD)) for o, v, _ in pts]
    chart["svg_points"] = " ".join(f"{fmt(x)},{fmt(y)}" for x, y in coords) if len(coords) >= 2 else ""
    if len(coords) >= 2:
        base = HERO_H - HERO_PAD
        d = ["M", f"{fmt(coords[0][0])},{fmt(coords[0][1])}"]
        for x, y in coords[1:]:
            d += ["L", f"{fmt(x)},{fmt(y)}"]
        d += ["L", f"{fmt(coords[-1][0])},{fmt(base)}",
              "L", f"{fmt(coords[0][0])},{fmt(base)}", "Z"]
        chart["svg_area_d"] = " ".join(d)
    else:
        chart["svg_area_d"] = ""
    chart["dots"] = [{"cx": fmt(x), "cy": fmt(y)} for x, y in coords]
    # per-point status drives the marker colour (amber outline when out of range)
    statuses = [range_status(v, ref) for _, v, _ in pts]
    for dot, st in zip(chart["dots"], statuses):
        stroke, fill = point_colour(st)
        dot["stroke"] = stroke
        dot["fill"] = fill if fill != "none" else CARD


def enrich(data: dict) -> dict:
    for chart in data.get("trend_charts", []) or []:
        if isinstance(chart, dict):
            _enrich_series(chart, HERO_W, HERO_H, HERO_PAD, with_area=True, with_dots=True)
            _enrich_markers(chart, HERO_W, HERO_PAD)
            _enrich_reference_band(chart)
    for row in data.get("lab_trends", []) or []:
        if isinstance(row, dict):
            _enrich_series(row, SPARK_W, SPARK_H, SPARK_PAD, with_area=False)
    return data


# ── anti-fabrication gate (G-CHART-2) ────────────────────────────────────────
def _source_index(paths):
    idx: dict[str, set] = {}

    def add(metric, value):
        if metric is None:
            return
        key = str(metric).strip().lower()
        bucket = idx.setdefault(key, set())
        f = to_float(value)
        if f is not None:
            bucket.add(("num", round(f, 6)))
        bucket.add(("str", str(value).strip()))

    for p in paths:
        if not p:
            continue
        try:
            doc = json.loads(Path(p).read_text(encoding="utf-8"))
        except Exception:
            continue
        if not isinstance(doc, dict):
            continue
        for o in doc.get("observations", []):
            if isinstance(o, dict):
                add(o.get("metric"), o.get("value"))
        for panel in doc.get("panels", []):
            if not isinstance(panel, dict):
                continue
            analyte = panel.get("analyte")
            for v in panel.get("values", []) or []:
                if isinstance(v, dict):
                    add(analyte, v.get("value"))
        for row in doc.get("labs", []) or []:
            if isinstance(row, dict):
                name = row.get("lab_name") or row.get("name") or row.get("analyte")
                val = row.get("value") if row.get("value") is not None else row.get("lab_value")
                add(name, val)
    return idx


def _value_backed(idx, metric, raw_value) -> bool:
    if metric is None:
        return False
    bucket = idx.get(str(metric).strip().lower())
    if not bucket:
        return False
    f = to_float(raw_value)
    if f is not None and ("num", round(f, 6)) in bucket:
        return True
    return ("str", str(raw_value).strip()) in bucket


def _integrity_violations(data, idx):
    bad = []
    for chart in data.get("trend_charts", []) or []:
        if isinstance(chart, dict) and isinstance(chart.get("series"), list):
            for p in chart["series"]:
                if isinstance(p, dict) and to_float(p.get("v")) is not None:
                    if not _value_backed(idx, chart.get("metric"), p.get("v")):
                        bad.append(f"trend_charts[{chart.get('metric')!r}] value {p.get('v')!r} @ {p.get('t')!r}")
    for row in data.get("lab_trends", []) or []:
        if isinstance(row, dict) and isinstance(row.get("series"), list):
            for p in row["series"]:
                if isinstance(p, dict) and to_float(p.get("v")) is not None:
                    if not _value_backed(idx, row.get("lab_name"), p.get("v")):
                        bad.append(f"lab_trends[{row.get('lab_name')!r}] value {p.get('v')!r} @ {p.get('t')!r}")
    return bad


# ═════════════════════════════════════════════════════════════════════════════
# CHANNEL B — recipes
# ═════════════════════════════════════════════════════════════════════════════
def _pts_from_spec(series):
    """Normalise a spec series into ordered point dicts."""
    out = []
    for p in series or []:
        if not isinstance(p, dict):
            continue
        o = to_ordinal(p.get("t"))
        v = to_float(p.get("v"))
        out.append({
            "o": o, "v": v, "raw": p.get("v"), "t": p.get("t"),
            "unit": p.get("unit"), "method": p.get("method"),
            "ref": p.get("reference_range"), "critical": bool(p.get("critical")),
            "censor": censoring(p.get("v")),
        })
    out.sort(key=lambda p: (p["o"] is None, p["o"] or 0))
    return out


def _date_label(t) -> str:
    s = str(t or "")
    return s[:7] if len(s) >= 7 else s


# ── C1 · trend with reference band ───────────────────────────────────────────
def recipe_trend(spec):
    metric = spec.get("metric", "")
    unit = spec.get("unit", "")
    pts = [p for p in _pts_from_spec(spec.get("series")) if p["v"] is not None and p["o"] is not None]
    if len(pts) < 2:
        raise Eligibility("序列不足 2 个可比数据点，无法绘制趋势图。")
    ref = parse_reference_range(spec.get("reference_range")
                                or next((p["ref"] for p in pts if p["ref"]), None))
    h = 150.0
    tax = TimeAxis([p["o"] for p in pts], FIG_W, FIG_PAD)
    vax = ValueAxis([p["v"] for p in pts], h, 22.0, ref=ref)
    svg = Svg(FIG_W, h, label=f"{metric} 随时间的测量值")
    dropped, gaps_drawn = [], []

    # furniture first — the band and rails live under the data
    band_squashed = False
    if ref:
        lo, hi = ref
        y_lo = vax.y(lo) if lo is not None else h - 22.0
        y_hi = vax.y(hi) if hi is not None else 22.0
        # A value far above the range (CA19-9 412 against 0–37) squashes the band
        # to a hairline. Enforce a visible minimum so it stays legible, and SAY
        # in the reading note that it is no longer to scale — a band you cannot
        # see and a band you happen to sit inside look identical otherwise.
        if abs(y_lo - y_hi) < 4.0:
            band_squashed = True
            mid = (y_lo + y_hi) / 2
            y_hi, y_lo = mid - 2.0, mid + 2.0
        svg.band(FIG_PAD, FIG_W - FIG_PAD, y_hi, y_lo)
        edge = []
        if lo is not None:
            edge.append((lo, y_lo))
        if hi is not None:
            edge.append((hi, y_hi))
        # de-collide the two boundary labels; when they cannot both fit, keep the
        # bound the data is actually near and put the full range in the note
        if len(edge) == 2 and abs(edge[0][1] - edge[1][1]) < 9.0:
            near = max(edge, key=lambda e: sum(1 for p in pts if abs(p["v"] - e[0]) < abs(p["v"] - edge[0][0])))
            edge = [near] if band_squashed else [edge[0], (edge[1][0], edge[1][1] - 9.0)]
        for val, yy in edge:
            svg.line(FIG_PAD, yy, FIG_W - FIG_PAD, yy, stroke=LADDER[3], width=0.6, dash="3 3")
            svg.text(FIG_W - FIG_PAD + 2, yy + 3, _num(val), size=FS_AXIS, fill=MUTED)
    svg.rail(FIG_PAD, FIG_W - FIG_PAD, h - 20.0, ticks=[tax.x(p["o"]) for p in pts])

    # split the polyline wherever the method changes: connecting across a method
    # change would assert comparability we do not have
    segs, cur = [], [pts[0]]
    for a, b in zip(pts, pts[1:]):
        if (a.get("method") or None) != (b.get("method") or None):
            segs.append(cur)
            cur = [b]
        else:
            cur.append(b)
    segs.append(cur)
    # A long silence must not be drawn as a solid line. A 1.4-year gap rendered
    # as a straight segment reads as "it declined steadily through here", when in
    # fact nothing is known about that stretch — same class of error as joining
    # across a method change. Draw those spans dashed and name them in the note.
    ords_all = [p["o"] for p in pts]
    steps = [b - a for a, b in zip(ords_all, ords_all[1:])]
    med = sorted(steps)[len(steps) // 2] if steps else 0
    gap_min = max(120, med * 3) if med else 120
    for seg in segs:
        for a, b in zip(seg, seg[1:]):
            wide = (b["o"] - a["o"]) >= gap_min
            svg.polyline([(tax.x(a["o"]), vax.y(a["v"])), (tax.x(b["o"]), vax.y(b["v"]))],
                         stroke=PRIMARY_HI, width=1.8,
                         dash="5 4" if wide else None)
            if wide:
                gaps_drawn.append(b["o"] - a["o"])
    for a, b in zip(segs, segs[1:]):
        svg.line(tax.x(a[-1]["o"]), vax.y(a[-1]["v"]),
                 tax.x(b[0]["o"]), vax.y(b[0]["v"]),
                 stroke=LADDER[3], width=1.0, dash="2 3")

    # data points, coloured by range status (amber outline = out of range)
    label_x = [tax.x(p["o"]) for p in pts]
    placer = LabelPlacer()
    placer.reserve(0, h - 22, FIG_W, h)          # keep labels off the date axis
    for _v, _y in (edge if ref else []):
        # only the band's own tick label, not the whole right-hand column —
        # reserving the column silently swallowed the last point's value
        placer.reserve(FIG_W - FIG_PAD, _y - 5, FIG_W, _y + 5)
    for p, lx in zip(pts, label_x):
        st = range_status(p["v"], ref)
        stroke, fill = point_colour(st, p["critical"])
        y = vax.y(p["v"])
        if p.get("censor"):
            # censored reading: hollow square + a whisker pointing the way the
            # true value lies, so a bound never reads as a measurement
            svg.rect(lx - 2.6, y - 2.6, 5.2, 5.2, fill=CARD, stroke=stroke, width=1.4)
            dy = 5.0 if p["censor"] == "left" else -5.0
            svg.line(lx, y + (2.6 if dy > 0 else -2.6), lx, y + dy,
                     stroke=stroke, width=1.2)
            svg.raw(f'<title>{esc(str(p["raw"]) + _u(unit))} @ {esc(p["t"])}'
                    f'（超出检测限，按限值绘制）</title>')
        else:
            svg.circle(lx, y, 2.8, fill=(CARD if fill == "none" else fill),
                       stroke=stroke, width=1.6,
                       title=f'{p["raw"]}{_u(unit)} @ {p["t"]}')
        ly = placer.place(lx, y, p["raw"], FS_VALUE, gap=6.0)
        if ly is None:
            # No clear slot: drop the label rather than print it on top of a
            # neighbour. The value stays reachable in the point's <title>, and
            # the reading note reports how many were dropped — an unreadable
            # smear of digits is worse than an honest omission.
            dropped.append(p)
        else:
            svg.text(lx, ly, f'{p["raw"]}', size=FS_VALUE, fill=INK,
                     anchor="middle", weight=700)
    # Date labels get their own pass. Two follow-ups a fortnight apart inside a
    # 1.8-year span land on the same pixel and print as "20226-06-07"; the axis
    # only needs enough dates to orient the reader, so drop the ones that would
    # collide — but never the last, which anchors "how recent is this?".
    MIN_DATE_GAP = 34.0
    keep, last_x = [], None
    for p, lx in zip(pts, label_x):
        if last_x is None or lx - last_x >= MIN_DATE_GAP:
            keep.append((p, lx))
            last_x = lx
    if keep and keep[-1][0] is not pts[-1]:
        if label_x[-1] - keep[-1][1] < MIN_DATE_GAP:
            keep.pop()
        keep.append((pts[-1], label_x[-1]))
    for p, lx in keep:
        svg.text(lx, h - 9, _date_label(p["t"]), size=FS_AXIS, fill=MUTED, anchor="middle")

    note, caveats = reading_note(pts, unit, ref, spec.get("reference_source"))
    if gaps_drawn:
        longest = max(gaps_drawn)
        caveats.append(f"图中虚线段表示这期间档案里没有该指标的记录（最长一段约 "
                       f"{_humanise_days(longest)}），线只是把两端的点连起来，"
                       f"不代表这段时间的真实变化。")
    if dropped:
        caveats.append(f"有 {len(dropped)} 个点的数值因为时间靠得太近，标在图上会互相压住，"
                       f"已省略数字标签（点仍在图上，把鼠标停在点上可看到具体数值）。"
                       f"完整数值见下方或原报告。")
    if band_squashed:
        lo, hi = ref
        rng = (f"{_num(lo)}–{_num(hi)}" if lo is not None and hi is not None
               else (f"≤{_num(hi)}" if hi is not None else f"≥{_num(lo)}"))
        caveats.append(f"图中数值远离参考区间（{rng}{_u(unit)}），区间带已按最小高度显示，"
                       f"不代表其真实宽度。")
    legend = ["● 参考区间内", "○ 参考区间外（琥珀描边）"] if ref else []
    if any(p["critical"] for p in pts):
        legend.append("● 源报告标注危急值")
    return svg, note, legend, caveats, f"{metric}{_u(unit)}"


# ── C3 · treatment swimlane ──────────────────────────────────────────────────
def recipe_swimlane(spec):
    eps = [e for e in (spec.get("episodes") or []) if isinstance(e, dict)]
    if not eps:
        raise Eligibility("没有可绘制的治疗阶段记录。")
    rows_data = []
    for e in eps:
        o1, o2 = to_ordinal(e.get("start")), to_ordinal(e.get("end"))
        if o1 is None:
            continue
        rows_data.append({"o1": o1, "o2": o2, "label": e.get("label") or e.get("regimen") or "",
                          "intent": e.get("intent") or "", "open": o2 is None,
                          "start": e.get("start"), "end": e.get("end")})
    if not rows_data:
        raise Eligibility("治疗阶段缺少可解析的开始日期。")
    rows_data.sort(key=lambda r: r["o1"])
    all_o = [r["o1"] for r in rows_data] + [r["o2"] for r in rows_data if r["o2"] is not None]
    lane_h, top = 20.0, 26.0
    h = top + lane_h * len(rows_data) + 26.0
    tax = TimeAxis(all_o, FIG_W, 96.0)  # wide left pad for the regimen names
    svg = Svg(FIG_W, h, label="治疗阶段时间轴")

    for i, r in enumerate(rows_data):
        y = top + i * lane_h
        svg.line(6, y + lane_h / 2, FIG_W - FIG_PAD, y + lane_h / 2, stroke=RULE, width=0.5)
        shown, full = truncate(r["label"], 12)
        svg.text(6, y + lane_h / 2 + 3, shown, size=FS_BODY, fill=INK, weight=600,
                 title=full if full != shown else None)
        x1 = tax.x(r["o1"])
        x2 = tax.x(r["o2"]) if r["o2"] is not None else FIG_W - FIG_PAD
        shade = LADDER[min(4, 1 + i % 3)]
        svg.rect(x1, y + 4, max(2.0, x2 - x1), lane_h - 10, fill=shade, rx=2.0)
        if r["open"]:
            # open-ended episode: dashed tail, never a hard edge implying an end
            svg.line(x2 - 12, y + lane_h / 2, x2 + 4, y + lane_h / 2,
                     stroke=PRIMARY, width=1.0, dash="2 2")
        # intent label always sits after the bar, in one consistent column —
        # placing it inside when it happens to fit made the three lanes read as
        # three different chart conventions
        if r["intent"]:
            svg.text(x2 + 6, y + lane_h / 2 + 3, str(r["intent"])[:6],
                     size=FS_BODY, fill=MUTED_DEEP)
    # time rail — one tick per episode boundary, labels de-collided by month
    yb = top + lane_h * len(rows_data) + 6
    tick_xs = [tax.x(o) for o in sorted(set(all_o))]
    svg.rail(96.0, FIG_W - FIG_PAD, yb, ticks=tick_xs)
    import datetime as _dt
    labelled = []
    for o in sorted(set(all_o)):
        x = tax.x(o)
        lbl = _date_label(_dt.date.fromordinal(o).isoformat())
        if any(abs(x - lx) < 34.0 for lx, _ in labelled) or any(l == lbl for _, l in labelled):
            continue
        labelled.append((x, lbl))
        svg.text(x, yb + 11, lbl, size=FS_AXIS, fill=MUTED, anchor="middle")

    note = (f"{len(rows_data)} 段治疗记录，按源报告的开始与结束日期排布"
            f"{'；虚线尾表示记录中未写结束日期' if any(r['open'] for r in rows_data) else ''}。")
    caveats = ["时间对齐不表示疗效或因果。各段的划分与命名取自源病历记录。"]
    return svg, note, [], caveats, "治疗阶段"


# ── C4 · lab panel reference bars ────────────────────────────────────────────
def recipe_panel(spec):
    rows = [r for r in (spec.get("rows") or []) if isinstance(r, dict)]
    if not rows:
        raise Eligibility("没有可绘制的检验项目。")
    lane, top, lx = 17.0, 24.0, 108.0
    h = top + lane * len(rows) + 16.0
    svg = Svg(FIG_W, h, label="检验项目与参考区间对照")
    track_x1, track_x2 = lx, FIG_W - 76.0
    for i, r in enumerate(rows):
        y = top + i * lane
        name, full = truncate(r.get("analyte", ""), 13)
        svg.text(6, y + 4, name, size=FS_BODY, fill=INK, weight=600,
                 title=full if full != name else None)
        ref = parse_reference_range(r.get("reference_range"))
        v = to_float(r.get("value"))
        svg.line(track_x1, y, track_x2, y, stroke=RULE, width=0.5)
        if ref and v is not None:
            lo, hi = ref
            # normalise onto the track: the band occupies the middle 60%
            lo_e = lo if lo is not None else min(v, hi if hi is not None else v) * 0.5
            hi_e = hi if hi is not None else max(v, lo_e) * 1.5
            spanv = max(_EPS, hi_e - lo_e)
            dom_lo, dom_hi = lo_e - spanv * 0.6, hi_e + spanv * 0.6
            dom_lo, dom_hi = min(dom_lo, v), max(dom_hi, v)
            def px(val):
                return track_x1 + (val - dom_lo) / max(_EPS, dom_hi - dom_lo) * (track_x2 - track_x1)
            svg.rect(px(lo_e), y - 4.5, px(hi_e) - px(lo_e), 9, fill=BAND, rx=1.5)
            st = range_status(v, ref)
            stroke, fill = point_colour(st, bool(r.get("critical")))
            svg.circle(px(v), y, 3.0, fill=(CARD if fill == "none" else fill),
                       stroke=stroke, width=1.6,
                       title=f'{r.get("value")} {r.get("unit","")} · 参考 {r.get("reference_range","")}')
            svg.text(track_x2 + 5, y + 3.5, f'{r.get("value")}{_u(r.get("unit"))}',
                     size=FS_BODY, fill=INK, weight=700)
        else:
            # No parseable range (or a non-numeric result like 阴性/阳性): keep the
            # row visually intact — a gap in the track reads as missing data, when
            # in fact the VALUE is present and only the band is absent.
            svg.line(track_x1, y, track_x2, y, stroke=RULE, width=0.5, dash="2 3")
            svg.text(track_x1 + 4, y + 3.5, f'{r.get("value","")}{_u(r.get("unit"))}',
                     size=FS_BODY, fill=INK, weight=700)
            svg.text(track_x2 + 5, y + 3.5, "无参考区间", size=FS_BODY, fill=MUTED)
    n_ref = sum(1 for r in rows if parse_reference_range(r.get("reference_range")))
    note = (f"{len(rows)} 个检验项目，{n_ref} 项带本次报告的参考区间"
            f"（淡紫带 = 参考区间，圆点 = 本次测量值）。")
    caveats = []
    if n_ref < len(rows):
        caveats.append(f"其中 {len(rows) - n_ref} 项本次报告未提供可解析的参考区间，"
                       f"未画区间带；不同实验室与方法的区间不同，不能套用通用值。")
    return svg, note, ["淡紫带 = 参考区间", "○ 琥珀描边 = 区间外"], caveats, "检验项目"


# ── C6 · event timeline ──────────────────────────────────────────────────────
def recipe_timeline(spec):
    evs = [e for e in (spec.get("events") or []) if isinstance(e, dict)]
    pts = [{"o": to_ordinal(e.get("t") or e.get("date")), "label": e.get("label") or e.get("title") or "",
            "kind": e.get("kind") or "", "t": e.get("t") or e.get("date")} for e in evs]
    pts = [p for p in pts if p["o"] is not None]
    if not pts:
        raise Eligibility("没有带可解析日期的事件。")
    pts.sort(key=lambda p: p["o"])
    xs_probe = TimeAxis([p["o"] for p in pts], FIG_W, FIG_PAD)
    rows_probe = stack_rows([xs_probe.x(p["o"]) for p in pts], 62.0, 0.0, 1.0)
    n_rows = max(rows_probe) + 1
    axis_y = 26.0 + n_rows * 15.0          # canvas grows with the label stack
    h = axis_y + 34.0                       # instead of leaving dead space above
    tax = xs_probe
    svg = Svg(FIG_W, h, label="病程事件时间轴")
    xs = [tax.x(p["o"]) for p in pts]
    svg.rail(FIG_PAD, FIG_W - FIG_PAD, axis_y, ticks=xs, tick_h=3.0)
    for p, x, r in zip(pts, xs, rows_probe):
        ly = axis_y - 12 - r * 15
        svg.line(x, ly + 3, x, axis_y, stroke=LADDER[3], width=0.6, dash="2 2")
        svg.circle(x, axis_y, 2.6, fill=PRIMARY, stroke=PRIMARY, width=0.8)
        shown, full = truncate(p["label"], 9)
        svg.text(x, ly, shown, size=FS_BODY, fill=INK, anchor="middle", weight=600,
                 title=full if full != shown else None)
    # Date labels get their OWN de-collision pass: two events in the same month
    # collapse to one label ("2026-012026-01" is what happens otherwise), and
    # labels closer than a label-width are stacked onto a second row.
    date_rows = stack_rows(xs, 40.0, 0.0, 1.0)
    seen_labels = set()
    for p, x, dr in zip(pts, xs, date_rows):
        lbl = _date_label(p["t"])
        if lbl in seen_labels:
            continue          # month already on the axis — repeating it is noise
        seen_labels.add(lbl)
        svg.text(x, axis_y + 11 + dr * 10, lbl, size=FS_AXIS, fill=MUTED, anchor="middle")
    note = f"{len(pts)} 个事件，按源记录日期排布，横轴按真实时间间隔。"
    return svg, note, [], ["事件的先后顺序不表示因果关系。"], "病程事件"


# ── C7 · variant VAF rows ────────────────────────────────────────────────────
def recipe_vaf(spec):
    rows = [r for r in (spec.get("variants") or []) if isinstance(r, dict)]
    rows = [r for r in rows if to_float(r.get("vaf")) is not None]
    if not rows:
        raise Eligibility("没有带数值 VAF 的变异记录。")
    rows.sort(key=lambda r: -to_float(r.get("vaf")))
    lane, top, lx = 18.0, 26.0, 132.0
    h = top + lane * len(rows) + 14.0
    svg = Svg(FIG_W, h, label="变异等位基因频率")
    x2 = FIG_W - 60.0
    # unit grid: a post every 10% so the bar is countable, not just comparable
    for pct in range(0, 101, 10):
        gx = lx + (x2 - lx) * pct / 100.0
        svg.line(gx, top - 6, gx, top + lane * len(rows) - 6, stroke=RULE, width=0.4)
        if pct % 20 == 0:
            svg.text(gx, top - 9, f"{pct}%", size=FS_AXIS, fill=MUTED, anchor="middle")
    for i, r in enumerate(rows):
        y = top + i * lane
        gene = r.get("gene") or ""
        change = r.get("change") or r.get("hgvs") or ""
        shown, full = truncate(f"{gene} {change}".strip(), 17)
        svg.text(6, y + 3, shown, size=FS_BODY, fill=INK, weight=600,
                 title=full if full != shown else None)
        v = to_float(r.get("vaf"))
        v = v * 100 if v <= 1.0 else v
        w = (x2 - lx) * max(0.0, min(100.0, v)) / 100.0
        svg.rect(lx, y - 4.5, w, 9, fill=LADDER[3], rx=1.5)
        svg.text(lx + w + 4, y + 3, f"{v:g}%", size=FS_BODY, fill=INK, weight=700)
    note = (f"{len(rows)} 个变异的等位基因频率（VAF），按数值从高到低排列，"
            f"数值取自分子检测报告。")
    caveats = ["VAF 高低不代表临床重要性，也不表示可用药与否；"
               "变异的解读由主诊团队与分子病理结合报告全文判断。"]
    return svg, note, ["每格 10%"], caveats, "变异 VAF"


# ── C8 · documentation coverage gauge ────────────────────────────────────────
def recipe_coverage(spec):
    items = [r for r in (spec.get("items") or []) if isinstance(r, dict)]
    if not items:
        raise Eligibility("没有可展示的资料完整度条目。")
    lane, top, lx = 18.0, 22.0, 132.0
    h = top + lane * len(items) + 12.0
    svg = Svg(FIG_W, h, label="资料完整度")
    x2 = FIG_W - 70.0
    for i, it in enumerate(items):
        y = top + i * lane
        shown, full = truncate(it.get("label", ""), 17)
        svg.text(6, y + 3, shown, size=FS_BODY, fill=INK, weight=600,
                 title=full if full != shown else None)
        have, need = to_float(it.get("have")), to_float(it.get("need"))
        svg.rect(lx, y - 5, x2 - lx, 10, fill=LADDER[0], rx=2.0)
        if have is not None and need and need > 0:
            frac = max(0.0, min(1.0, have / need))
            svg.rect(lx, y - 5, (x2 - lx) * frac, 10, fill=LADDER[3], rx=2.0)
            # countable unit posts — each notch is one document
            if need <= 24:
                for k in range(1, int(need)):
                    gx = lx + (x2 - lx) * k / need
                    svg.line(gx, y - 5, gx, y + 5, stroke=CARD, width=0.7)
            svg.text(x2 + 5, y + 3, f"{int(have)}/{int(need)}", size=FS_BODY,
                     fill=INK, weight=700)
        else:
            svg.text(x2 + 5, y + 3, str(it.get("have", "—")), size=FS_BODY, fill=MUTED)
    note = f"{len(items)} 类资料的收集情况（每格 = 1 份文件）。"
    caveats = ["完整度只统计已上传的文件数量，不评价资料的临床充分性。"]
    return svg, note, [], caveats, "资料完整度"


# ── C9 · two-timepoint dumbbell ──────────────────────────────────────────────
def recipe_dumbbell(spec):
    rows = [r for r in (spec.get("rows") or []) if isinstance(r, dict)]
    rows = [r for r in rows
            if to_float(r.get("v1")) is not None and to_float(r.get("v2")) is not None]
    if not rows:
        raise Eligibility("没有同时具备两个时点数值的项目。")
    lane, top, lx = 21.0, 34.0, 116.0
    h = top + lane * len(rows) + 16.0
    svg = Svg(FIG_W, h, label="两个时点的数值对照")
    x2 = FIG_W - 84.0
    # PER-ROW normalisation. A shared value axis across rows would put 68 kg and
    # 132 g/L on one scale, making bar length a comparison between quantities
    # that have no common dimension — the chart would read as "haemoglobin moved
    # more than weight", which is meaningless. Each row is scaled to its OWN two
    # values, so length encodes only that row's movement, and the legend says so.
    svg.text(lx, top - 14, esc(spec.get("t1_label", "时点 1")), size=FS_AXIS, fill=MUTED)
    svg.text(x2, top - 14, esc(spec.get("t2_label", "时点 2")), size=FS_AXIS,
             fill=MUTED, anchor="end")
    for i, r in enumerate(rows):
        y = top + i * lane
        shown, full = truncate(r.get("label", ""), 15)
        svg.text(6, y + 3, shown, size=FS_BODY, fill=INK, weight=600,
                 title=full if full != shown else None)
        a, b = to_float(r["v1"]), to_float(r["v2"])
        # Position encodes the value as a FRACTION OF THAT ROW'S OWN maximum, so
        # x means something (how far this reading sits below its own peak) and
        # the segment length means something (how much it moved, proportionally).
        # It must NOT be ordered by magnitude: doing that put "68.0 → 61.5" on
        # screen as 61.5 on the left, silently reversing time. Which end is
        # earlier is carried by the marker (hollow = first), never by position.
        rmax = max(abs(a), abs(b)) or 1.0
        def rx(v):
            return lx + (x2 - lx) * (0.08 + 0.86 * (v / rmax))
        xa, xb = rx(a), rx(b)
        svg.line(lx, y, x2, y, stroke=RULE, width=0.5)
        svg.line(min(xa, xb), y, max(xa, xb), y, stroke=LADDER[2], width=2.4, cap="round")
        svg.circle(xa, y, 3.2, fill=CARD, stroke=MUTED, width=1.5,
                   title=f"{spec.get('t1_label','时点 1')}: {r['v1']}")
        svg.circle(xb, y, 3.2, fill=PRIMARY, stroke=PRIMARY, width=1.5,
                   title=f"{spec.get('t2_label','时点 2')}: {r['v2']}")
        svg.text(x2 + 6, y + 3, f"{r['v1']} → {r['v2']}{_u(r.get('unit'))}",
                 size=FS_BODY, fill=INK)
    note = (f"{len(rows)} 个项目在两个时点的数值对照"
            f"（空心 = {spec.get('t1_label','时点 1')}，实心 = {spec.get('t2_label','时点 2')}）。"
            f"每行按该行自身的最大值缩放，位置表示占该行最大值的比例。")
    caveats = ["各行的单位与量纲不同，行与行之间的线段长度不可互相比较，只看每行自身的方向与数值。",
               "两个时点之间发生的其他情况未在图中体现，数值变化的原因需由主诊团队判断。"]
    return svg, note, [], caveats, "两时点对照"


# ── C10 · medication colonnade ───────────────────────────────────────────────
def recipe_medications(spec):
    meds = [m for m in (spec.get("medications") or []) if isinstance(m, dict)]
    if not meds:
        raise Eligibility("没有可展示的用药记录。")
    groups = {}
    for m in meds:
        groups.setdefault(m.get("group") or "未分组", []).append(m)
    order = sorted(groups, key=lambda k: -len(groups[k]))
    lane, gap, top = 13.0, 10.0, 24.0
    h = top + sum(lane * len(groups[g]) + gap + 12 for g in order) + 8.0
    svg = Svg(FIG_W, h, label="用药清单按类别归属")
    y = top
    for g in order:
        svg.text(6, y, f"{g}", size=FS_BODY, fill=PRIMARY, weight=700)
        svg.text(FIG_W - FIG_PAD, y, f"{len(groups[g])}", size=FS_BODY, fill=MUTED,
                 anchor="end", weight=700)
        svg.line(6, y + 3.5, FIG_W - FIG_PAD, y + 3.5, stroke=RULE, width=0.6)
        y += 12
        for m in groups[g]:
            svg.circle(11, y - 2.5, 1.8, fill=LADDER[3], stroke=LADDER[4], width=0.6)
            shown, full = truncate(m.get("name", ""), 22)
            svg.text(18, y, shown, size=FS_BODY, fill=INK,
                     title=full if full != shown else None)
            if m.get("note"):
                svg.text(FIG_W - FIG_PAD, y, str(m["note"])[:16], size=FS_BODY,
                         fill=MUTED, anchor="end")
            y += lane
        y += gap
    note = f"{len(meds)} 项用药记录，按源病历中的类别归组（每个点 = 一条记录）。"
    caveats = ["清单为源病历的转录，不代表当前仍在使用，也不含相互作用评估。"]
    return svg, note, [], caveats, "用药清单"


# ── 库外图型示例 · 用药重叠密度 ─────────────────────────────────────────────
# NOT in the original catalogue. Added by following SKILL.md §清单外的图:
#   1. ontology — x = calendar time, step height = how many drugs were in use
#      simultaneously on that day, lane bars = which drug covers which span.
#      Every channel maps to a counted fact from the record; nothing is inferred.
#   2. nearest clinical relative — `swimlane` (interval data on a time axis);
#      its lane layout and open-ended-tail convention are reused verbatim.
#   3. assembled from primitives only — TimeAxis / stack_rows / Svg.rail /
#      truncate / the token table. No new colour, no new font size.
#   4. passes the same gates as every catalogue recipe (G-CHART-8).
# It exists to prove the generalisation path is real rather than aspirational.
def recipe_med_overlap(spec):
    meds = [m for m in (spec.get("medications") or []) if isinstance(m, dict)]
    rows = []
    for m in meds:
        o1, o2 = to_ordinal(m.get("start")), to_ordinal(m.get("end"))
        if o1 is None:
            continue
        rows.append({"o1": o1, "o2": o2, "open": o2 is None,
                     "name": m.get("name") or ""})
    if not rows:
        raise Eligibility("没有带可解析开始日期的用药记录。")
    rows.sort(key=lambda r: r["o1"])
    lo = min(r["o1"] for r in rows)
    # An open-ended entry runs to the end of the charted window, not to its own
    # start day. Collapsing it to zero width would render "still taking this" as
    # a one-day course — the opposite of what the record says.
    hi = max([r["o2"] for r in rows if r["o2"] is not None] or [lo])
    for r in rows:
        if r["o2"] is None:
            r["o2"] = hi
    # step series: concurrent count per day boundary (counted, not modelled)
    edges = sorted({r["o1"] for r in rows} | {r["o2"] for r in rows})
    counts = [(e, sum(1 for r in rows if r["o1"] <= e <= r["o2"])) for e in edges]
    peak = max(c for _, c in counts)

    lane_h, top = 15.0, 24.0
    step_h = 74.0
    h = top + step_h + 10 + lane_h * len(rows) + 30.0
    tax = TimeAxis([lo, hi], FIG_W, 96.0)
    vax = ValueAxis([0, peak], step_h, 12.0, include_zero=True)
    svg = Svg(FIG_W, h, label="同时在用的药物数量与各药覆盖区间")

    # furniture: one horizontal rung per drug count, so the step is countable
    for k in range(0, peak + 1):
        y = top + vax.y(k)
        svg.line(96.0, y, FIG_W - FIG_PAD, y, stroke=RULE, width=0.5)
        svg.text(92.0, y + 3, str(k), size=FS_AXIS, fill=MUTED, anchor="end")
    svg.text(92.0, top - 6, "同时在用", size=FS_AXIS, fill=MUTED_DEEP, anchor="end")

    pts = []
    for (e, c) in counts:
        x = tax.x(e)
        if pts:
            pts.append((x, pts[-1][1]))   # hold previous level → true step, no ramp
        pts.append((x, top + vax.y(c)))
    svg.polyline(pts, stroke=PRIMARY_HI, width=1.6)

    lane_top = top + step_h + 10
    for i, r in enumerate(rows):
        y = lane_top + i * lane_h
        shown, full = truncate(r["name"], 12)
        svg.text(6, y + 3, shown, size=FS_BODY, fill=INK, weight=600,
                 title=full if full != shown else None)
        x1, x2 = tax.x(r["o1"]), tax.x(r["o2"])
        svg.rect(x1, y - 3.5, max(2.0, x2 - x1), 7, fill=LADDER[min(4, 1 + i % 3)], rx=1.5)
        if r["open"]:
            svg.line(x2, y, x2 + 10, y, stroke=PRIMARY, width=1.0, dash="2 2")
    import datetime as _dt
    yb = lane_top + lane_h * len(rows) + 6
    svg.rail(96.0, FIG_W - FIG_PAD, yb, ticks=[tax.x(e) for e in edges])
    labelled, seen = [], set()
    for e in edges:
        x = tax.x(e)
        lbl = _date_label(_dt.date.fromordinal(e).isoformat())
        if lbl in seen or any(abs(x - px) < 34.0 for px in labelled):
            continue
        seen.add(lbl)
        labelled.append(x)
        svg.text(x, yb + 11, lbl, size=FS_AXIS, fill=MUTED, anchor="middle")

    note = (f"{len(rows)} 种用药的覆盖区间，以及每一天同时在用的药物数量"
            f"（阶梯线，最高 {peak} 种）。日期与起止取自源病历记录。")
    caveats = ["同时在用只统计记录中的用药区间重叠，不代表相互作用、不良反应或用药合理性；"
               "相互作用评估请交由主诊团队或临床药师。",
               "记录中未写结束日期的用药以虚线尾表示，不代表已停用。"]
    return svg, note, [f"阶梯 = 同时在用药物数（0–{peak}）"], caveats, "用药重叠"


class Eligibility(Exception):
    """Raised when data does not qualify for the requested chart. The message is
    shown to the patient verbatim: saying WHY there is no chart ('目前只有一次
    记录') is useful information, and silently omitting the chart is not."""


RECIPES = {
    "trend": recipe_trend,            # C1
    "swimlane": recipe_swimlane,      # C3
    "panel": recipe_panel,            # C4
    "timeline": recipe_timeline,      # C6
    "vaf": recipe_vaf,                # C7
    "coverage": recipe_coverage,      # C8
    "dumbbell": recipe_dumbbell,      # C9
    "medications": recipe_medications,  # C10
    "med-overlap": recipe_med_overlap,  # 库外示例(见函数上方注释)
}


# ═════════════════════════════════════════════════════════════════════════════
# Loaders — build a spec straight from organize artefacts (paths B and C)
# ═════════════════════════════════════════════════════════════════════════════
def spec_from_longitudinal(path, metric):
    """Build a trend spec from longitudinal_observations.json for ONE analyte.

    ONE analyte, by contract: expanding to 'related' markers would put us back
    into deciding which marker is worth watching — exactly the cancer-type
    marker table that was withdrawn (see references/chart-eligibility.md §history
    and G-CHART-7).
    """
    doc = json.loads(Path(path).read_text(encoding="utf-8"))
    obs = [o for o in doc.get("observations", []) if isinstance(o, dict)]
    want = str(metric).strip().lower()
    hit = [o for o in obs if str(o.get("metric", "")).strip().lower() == want]
    if not hit:
        names = sorted({str(o.get("metric")) for o in obs if o.get("metric")})
        raise Eligibility(f"记录里没有找到指标 {metric!r}。"
                          f"现有指标：{'、'.join(names[:12]) or '（无）'}")
    series, units, refs = [], [], []
    for o in hit:
        series.append({
            "t": o.get("timestamp"), "v": o.get("value"),
            "unit": o.get("unit"), "method": o.get("method_or_device"),
            "reference_range": o.get("reference_range"),
            "critical": bool(o.get("critical") or o.get("abnormal_flag") in ("HH", "LL", "危急")),
        })
        if o.get("unit"):
            units.append(o["unit"])
        if o.get("reference_range"):
            refs.append(o["reference_range"])
    return {
        "metric": hit[0].get("metric"),
        "unit": units[-1] if units else "",
        "series": series,
        # the MOST RECENT report's range — never a textbook value (G-CHART-3)
        "reference_range": refs[-1] if refs else None,
        "reference_source": "本次报告" if refs else None,
    }


def spec_from_labs(path, metric):
    """Build a trend spec from labs.json panels[] for ONE analyte.

    Exists so nobody has to hand-write a spec (or a one-off converter) to chart a
    lab series. `--spec` bypasses the source-backed check, so every hand-typed
    number is an opportunity for a typo that no gate will catch; reading the
    panel directly keeps the values verbatim from the record.

    Matching is exact first, then a case-insensitive substring, because record
    analyte names carry their Chinese gloss ("CEA 癌胚抗原") while people ask for
    "CEA".
    """
    doc = json.loads(Path(path).read_text(encoding="utf-8"))
    panels = [p for p in doc.get("panels", []) if isinstance(p, dict)]
    want = str(metric).strip().lower()
    hit = next((p for p in panels if str(p.get("analyte", "")).strip().lower() == want), None)
    if hit is None:
        cands = [p for p in panels
                 if want in str(p.get("analyte", "")).lower()
                 or want in str(p.get("normalized_analyte", "")).lower()]
        if len(cands) == 1:
            hit = cands[0]
        elif len(cands) > 1:
            names = "、".join(str(c.get("analyte")) for c in cands)
            raise Eligibility(f"{metric!r} 匹配到多个项目：{names}。请用完整名称。")
    if hit is None:
        names = sorted({str(p.get("analyte")) for p in panels if p.get("analyte")})
        raise Eligibility(f"记录里没有找到项目 {metric!r}。"
                          f"现有项目：{'、'.join(names[:14]) or '（无）'}")
    vals = [v for v in (hit.get("values") or []) if isinstance(v, dict)
            and v.get("value") is not None]
    series, units, refs = [], [], []
    for v in vals:
        t = v.get("collected_at") or v.get("date") or v.get("reported_at") or v.get("timestamp")
        flag = str(v.get("flag") or v.get("abnormal_flag") or "").strip()
        series.append({
            "t": t, "v": v.get("value"), "unit": v.get("unit"),
            "method": v.get("method") or v.get("method_or_device"),
            "reference_range": v.get("reference_range"),
            "critical": flag in ("↑↑", "↓↓", "HH", "LL", "危急"),
        })
        if v.get("unit"):
            units.append(v["unit"])
        if v.get("reference_range"):
            refs.append(v["reference_range"])
    return {
        "metric": hit.get("analyte"),
        "unit": units[-1] if units else "",
        "series": series,
        "reference_range": refs[-1] if refs else None,
        "reference_source": "本次报告" if refs else None,
    }


# ═════════════════════════════════════════════════════════════════════════════
# Drivers
# ═════════════════════════════════════════════════════════════════════════════
def run_channel_b(args) -> int:
    if args.from_labs:
        if not args.metric:
            print("ERROR: --from-labs requires --metric", file=sys.stderr)
            return 2
        try:
            spec = spec_from_labs(args.from_labs, args.metric)
        except Eligibility as e:
            print(f"NOT ELIGIBLE: {e}", file=sys.stderr)
            return 5
        except Exception as e:
            print(f"ERROR: cannot read --from-labs: {e}", file=sys.stderr)
            return 2
    elif args.from_longitudinal:
        if not args.metric:
            print("ERROR: --from-longitudinal requires --metric", file=sys.stderr)
            return 2
        try:
            spec = spec_from_longitudinal(args.from_longitudinal, args.metric)
        except Eligibility as e:
            print(f"NOT ELIGIBLE: {e}", file=sys.stderr)
            return 5
        except Exception as e:
            print(f"ERROR: cannot read --from-longitudinal: {e}", file=sys.stderr)
            return 2
    else:
        try:
            spec = json.loads(Path(args.spec).read_text(encoding="utf-8"))
        except Exception as e:
            print(f"ERROR: cannot read/parse --spec: {e}", file=sys.stderr)
            return 2

    recipe = RECIPES.get(args.chart)
    if recipe is None:
        print(f"ERROR: unknown --chart {args.chart!r}. known: {', '.join(sorted(RECIPES))}. "
              f"A chart outside this list is a NEW RECIPE composed from chart_core "
              f"primitives — see SKILL.md §generalisation.", file=sys.stderr)
        return 2
    try:
        svg, note, legend, caveats, subject = recipe(spec)
    except Eligibility as e:
        print(f"NOT ELIGIBLE: {e}", file=sys.stderr)
        return 5

    title = args.title or f"{subject} · 源报告记录"
    # G-CHART-1 floor, AUTHORED text only (see the scope note at the gate).
    # `note`/`caveats`/`legend` are produced by the deterministic recipes above
    # and are governed by code review, not by this runtime regex.
    viol = verdict_violations(args.title, spec.get("title"), spec.get("caption"))
    if viol:
        for text, phrase in viol:
            print(f"ERROR: verdict gate — {phrase!r} in {text!r}", file=sys.stderr)
        return 4

    src = args.source or "数据来源：本人上传的检验/病历报告，数值逐条转录，未做换算或推断。"
    html = page(title, note, svg.markup(), legend, src, caveats)
    out = Path(args.out_html)
    out.write_text(html, encoding="utf-8")
    print(f"chart → {out} ({len(html)} bytes, recipe={args.chart})")
    return 0


def run_channel_a(args) -> int:
    try:
        data = json.loads(Path(args.data).read_text(encoding="utf-8"))
    except Exception as e:
        print(f"ERROR: cannot read/parse --data: {e}", file=sys.stderr)
        return 2
    if not isinstance(data, dict):
        print("ERROR: --data root must be a JSON object", file=sys.stderr)
        return 2

    if args.longitudinal or args.labs:
        idx = _source_index([args.longitudinal, args.labs])
        violations = _integrity_violations(data, idx)
        if violations:
            print("ERROR: anti-fabrication gate — plotted value(s) absent from source store:",
                  file=sys.stderr)
            for v in violations:
                print(f"  - {v}", file=sys.stderr)
            return 3

    # G-CHART-1 floor over every caption-bearing field
    texts = []
    for c in (data.get("trend_charts") or []):
        if isinstance(c, dict):
            texts += [c.get("reading_note"), c.get("interpretation"), c.get("title")]
    viol = verdict_violations(*texts)
    if viol:
        for text, phrase in viol:
            print(f"ERROR: verdict gate — {phrase!r} in {text!r}", file=sys.stderr)
        return 4

    enrich(data)

    out = args.out or args.data
    Path(out).write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    n_charts = sum(1 for c in (data.get("trend_charts") or []) if isinstance(c, dict))
    n_labs = sum(1 for r in (data.get("lab_trends") or []) if isinstance(r, dict))
    print(f"enriched → {out} (trend charts={n_charts}, lab_trend rows={n_labs})")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Clinical chart geometry + standalone charts (deterministic, zero medical logic).")
    ap.add_argument("--data", help="channel A: case_summary_data.json to enrich in place")
    ap.add_argument("--out", help="channel A: output path (default: overwrite --data)")
    ap.add_argument("--longitudinal", help="longitudinal_observations.json (anti-fabrication gate / source)")
    ap.add_argument("--labs", help="labs.json (anti-fabrication gate)")
    ap.add_argument("--chart", help=f"channel B recipe: {', '.join(sorted(RECIPES))}")
    ap.add_argument("--spec", help="channel B: chart spec JSON")
    ap.add_argument("--from-longitudinal", dest="from_longitudinal",
                    help="channel B: build a trend spec from longitudinal_observations.json")
    ap.add_argument("--from-labs", dest="from_labs",
                    help="channel B: build a trend spec from labs.json panels[] "
                         "(use this instead of hand-writing --spec for lab series)")
    ap.add_argument("--metric", help="channel B: analyte name for --from-longitudinal")
    ap.add_argument("--out-html", dest="out_html", help="channel B: output HTML path")
    ap.add_argument("--title", help="channel B: reading-guide title (must pass the verdict gate)")
    ap.add_argument("--source", help="channel B: source line")
    args = ap.parse_args()

    if args.chart or args.out_html or args.spec or args.from_longitudinal or args.from_labs:
        if not args.out_html:
            print("ERROR: channel B requires --out-html", file=sys.stderr)
            return 2
        if not args.chart:
            args.chart = "trend"
        return run_channel_b(args)
    if args.data:
        return run_channel_a(args)
    ap.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
